services:
  app:
    build: .
    working_dir: /app
    command: ["php", "bin/console", "process:messages", "data/recruitment-task-source.json"]

  test:
    build: .
    working_dir: /app
    command: ["php", "vendor/bin/phpunit"]
