version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["php", "bin/console", "process:messages", "data/recruitment-task-source.json"]

  test:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: [ "./vendor/bin/phpunit" ]